blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/stateful-y/yohou_optuna/discussions
    about: Please use GitHub Discussions for questions and general discussions
  - name: Documentation
    url: https://stateful-y.github.io/yohou_optuna/
    about: Check the documentation for guides and API references
